from django.db import models

# Create your models here.
class Ganison_dataset_1(models.Model):
    school_name = models.CharField(max_length=255)
    year = models.IntegerField()
    StudentID = models.IntegerField()
    First_Name = models.CharField(max_length=255)
    Last_Name = models.CharField(max_length=255)
    Year_Level = models.IntegerField()
    Class = models.CharField(max_length=255)
    Subject = models.CharField(max_length=255)
    Answers = models.CharField(max_length=255)
    CorrectAnswers = models.CharField(max_length=255)
    Question_Number = models.IntegerField()
    SubjectContents = models.CharField(max_length=255)
    AssessmentAreas = models.CharField(max_length=255)
    sydney_correct_count_percentage = models.FloatField()
    sydney_average_score = models.FloatField()
    sydney_participants = models.IntegerField()
    student_score = models.FloatField()
    student_total_assessed = models.IntegerField()
    student_area_assessed_score = models.FloatField()
    total_area_assessed_score = models.FloatField()
    participant = models.IntegerField()
    correct_answer_percentage_per_class = models.FloatField()
    average_score = models.FloatField()
    school_percentile = models.IntegerField()
    sydney_percentile = models.IntegerField()
    strength_status = models.CharField(max_length=255)
    high_distinct_count = models.IntegerField()
    distinct_count = models.IntegerField()
    credit_count = models.IntegerField()
    participant_count = models.IntegerField()
    award = models.CharField(max_length=255)